### ISSUE TITLE
Feedback Task UTS

### ISSUE THREAD

**Issue by aufaroot18** [NelanJoe/kuliah-be#6]
## Feedback

- Thank you sudah mengerjakan final project.
- Sudah sesuai requirement.
- Terdapat autentikasi.

## Notes

- Pada response search by state, response yg dibalikin bisa disederhanakan lagi pada bagian switch case. Jika dilihat, isi response yg dibalikin sama di dalam bagian switch case, jadi bisa dibuat variable di luar switch case, lalu yg diubah cukup isi message-nya saja berdasarkan status.

## Improvement

- Coba lakukan normalisasi pada database. Ex: Bisa membuat table terpisah untuk status pasien.
- Gunakan eloquent relationship jika sudah melakukan normalisasi.

**Comment by NelanJoe** [comment]
> 

Terimakasih banyak bang @aufaroot18 atas masukkan dan sarannya, sejauh ini sangat terbantu belajar & kuliah dengan bang @aufaroot18

**Comment by aufaroot18** [comment]
Sama samaa, keep going and improving. :D
